Sharing feature
OxygenCobalt/Auxio pull request #443
Opened 2023-05-18 07:27 UTC by Koitharu

#### What is it?
- [ ] Bugfix (user facing)
- [x] Feature (user facing)
- [ ] Codebase improvement (dev facing)
- [ ] Meta improvement to the project (dev facing)

#### Description of changes
Actions to share songs files

#### Fixes the following issues
#347

#### APK testing
Soon

#### Due Diligence
- [x] I have read the [Contribution Guidelines](https://github.com/OxygenCobalt/Auxio/blob/dev/.github/CONTRIBUTING.md).
- [x] I have read the [Why Are These Features Missing?](https://github.com/OxygenCobalt/Auxio/wiki/Why-Are-These-Features-Missing%3F) page.

2023-05-18 15:35 UTC, OxygenCobalt requested changes
Very good work! I like how you stuck with the coding style used by the rest of the app. I'll do more thorough testing later, but here's some immediate things I noted.

2023-05-18 15:35 UTC, OxygenCobalt commented on app/src/main/java/org/oxycblt/auxio/music/fs/Fs.kt
> +        return fromFormat ?: fromExtension
`val raw: String get() = fromFormat ?: fromExtension`

2023-05-18 15:35 UTC, OxygenCobalt commented on app/src/main/java/org/oxycblt/auxio/util/ShareUtil.kt
Can you move this into `FrameworkUtil.kt`? It makes more sense there since this is android-platform-specific utilities.

2023-05-18 15:35 UTC, OxygenCobalt commented on app/src/main/java/org/oxycblt/auxio/util/ShareUtil.kt
> +fun Context.shareSong(song: Song) {
Generally I think I'd structure these methods as:

```
fun share(song: Song) = share(listOf(song))
fun share(songs: List<Song>) {
    // ...
}
```

Given the precedent set by classes like `MusicViewModel`. This is just a stylistic nit.

2023-05-22 16:47 UTC, OxygenCobalt commented
I actually have another question: Why exactly did you add sharing functionality for albums, artists, genres @Koitharu? That doesn't make much sense to me. Is there a specific app that benefits from such?

2023-05-22 17:33 UTC, Koitharu commented
As for me sometimes it is very useful ability to send all tracks from a specific album or artist

2023-05-24 02:51 UTC, kurokawaerne commented
I agree with him, the ability to share all the songs from an specific album/artist/playlist saves a lot of time. 

I've been testing this feature and works pretty well. I wonder if it's going to be included on a normal release.

2023-05-25 16:46 UTC, OxygenCobalt approved these changes
LGTM.

2023-05-25 16:46 UTC, merged